version: '3.3'

services:
    jenkins:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: Kinston-DockerJenkins
        restart: always
        ports:
            - "50000:50000"
            - "8080:8080"
        volumes:
            - ./jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
            - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose